config/routes.rb
Rails.application.routes.draw do

  root :to => "clients#index"
  
  resources :windows_events
  resources :events
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
		has_many :events
		has_many :windows_events
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :client
	default_scope -> { order('created_at DESC') }
	validates :client_id, presence: true
	has_many :windows_events
end

app/models/windows_event.rb
class WindowsEvent < ApplicationRecord
	belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
    respond_to do |format|
      format.html
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
    @events = @client.events.all
    respond_to do |format|
      format.html { @events }
      format.json { render json: @events }
    end
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        #format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        #format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:domain)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @windows_events = @event.windows_events.all
    respond_to do |format|
      format.html { @windows_events }
      format.json { render json: @windows_events }
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :client_id)
    end
end

app/controllers/windows_events_controller.rb
class WindowsEventsController < ApplicationController
  before_action :set_windows_event, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /windows_events
  # GET /windows_events.json
  def index
    @windows_events = WindowsEvent.all
  end

  # GET /windows_events/1
  # GET /windows_events/1.json
  def show
  end

  # GET /windows_events/new
  def new
    @windows_event = WindowsEvent.new
  end

  # GET /windows_events/1/edit
  def edit
  end

  # POST /windows_events
  # POST /windows_events.json
  def create
    @windows_event = WindowsEvent.new(windows_event_params)

    respond_to do |format|
      if @windows_event.save
        #format.html { redirect_to @windows_event, notice: 'Windows event was successfully created.' }
        format.json { render :show, status: :created, location: @windows_event }
      else
        #format.html { render :new }
        format.json { render json: @windows_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /windows_events/1
  # PATCH/PUT /windows_events/1.json
  def update
    respond_to do |format|
      if @windows_event.update(windows_event_params)
        format.html { redirect_to @windows_event, notice: 'Windows event was successfully updated.' }
        format.json { render :show, status: :ok, location: @windows_event }
      else
        format.html { render :edit }
        format.json { render json: @windows_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /windows_events/1
  # DELETE /windows_events/1.json
  def destroy
    @windows_event.destroy
    respond_to do |format|
      format.html { redirect_to windows_events_url, notice: 'Windows event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_windows_event
      @windows_event = WindowsEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def windows_event_params
      params.require(:windows_event).permit(:event_id, :client_id, :time, :samaccountname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/windows_events_helper.rb
module WindowsEventsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :domain %>
    <%= form.text_field :domain %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table class="table table-striped events">
    <thead class="thead-dark">
    <tr>
      <th>Domain</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to "#{client.domain}", client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Domain:</strong>
  <%= @client.domain %>
</p>

<div class="span8">
	<table class="table table-striped events">
		<thead class="thead-dark">
			<tr>
				<th scope="col">#</th>
				<th scope="col">Event ID</th>
				<th scope="col">Date</th>
			</tr>
		</thead>
		<tbody>
			<% @events.each do |event| %>
			<tr>
				<td scope="row"><%= event.id %></th>
				<td><%= link_to "#{event.name}", event %></th>
				<td> <%= event.created_at %></th>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/events/_event.html.erb
<li>
	<span class="content"><%= event.name %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(event.created_at) %> ago.
	</span>
</li>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.number_field :name %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.number_field :client_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.client_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Client:</strong>
  <%= @event.client_id %>
</p>

<div class="span8">
	<table class="table table-striped events">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Event ID</th>
				<th scope="col">SAMAccount Name</th>
				<th scope="col">Date</th>
			</tr>
		</thead>
		<tbody>
			<% @windows_events.each do |windows_event| %>
			<tr>
				<td scope="row"><%= @event.name %></th>
				<td><%= link_to "#{windows_event.samaccountname}", windows_event %></th>
				<td> <%= windows_event.time %></th>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/windows_events/_form.html.erb
<%= form_with(model: windows_event, local: true) do |form| %>
  <% if windows_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(windows_event.errors.count, "error") %> prohibited this windows_event from being saved:</h2>

      <ul>
      <% windows_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.number_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.number_field :client_id %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.date_select :time %>
  </div>

  <div class="field">
    <%= form.label :samaccountname %>
    <%= form.text_field :samaccountname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/windows_events/edit.html.erb
<h1>Editing Windows Event</h1>

<%= render 'form', windows_event: @windows_event %>

<%= link_to 'Show', @windows_event %> |
<%= link_to 'Back', windows_events_path %>

app/views/windows_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Windows Events</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Client</th>
      <th>Time</th>
      <th>Samaccountname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @windows_events.each do |windows_event| %>
      <tr>
        <td><%= windows_event.event_id %></td>
        <td><%= windows_event.client_id %></td>
        <td><%= windows_event.time %></td>
        <td><%= windows_event.samaccountname %></td>
        <td><%= link_to 'Show', windows_event %></td>
        <td><%= link_to 'Edit', edit_windows_event_path(windows_event) %></td>
        <td><%= link_to 'Destroy', windows_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Windows Event', new_windows_event_path %>

app/views/windows_events/new.html.erb
<h1>New Windows Event</h1>

<%= render 'form', windows_event: @windows_event %>

<%= link_to 'Back', windows_events_path %>

app/views/windows_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @windows_event.event_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @windows_event.client_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @windows_event.time %>
</p>

<p>
  <strong>Samaccountname:</strong>
  <%= @windows_event.samaccountname %>
</p>

<%= link_to 'Edit', edit_windows_event_path(@windows_event) %> |
<%= link_to 'Back', windows_events_path %>